### ISSUE TITLE
creating or opening a chanel regurns a error meassage

### ISSUE THREAD

**Issue by Eirik-Haukeland** [emilhauk/chitchat#14]
![image](https://github.com/emilhauk/chitchat/assets/50040667/866b9e49-4949-4eab-a332-d71f190049ba)

instead of opening a chat with messages and option to send a message i get "500"

**Comment by emilhauk** [comment]
The reason is that the app tries to load the users that have sent messages, but fails to handle that the channel is empty..

From the app logs:
`16:46:03 ERR Failed to load channel=92f07a72-d554-4ca6-ac0f-d49488263672 for user=1-13-37 error="failed to enhance messages for channel=92f07a72-d554-4ca6-ac0f-d49488263672: empty slice passed to 'in' query"`
